// <auto-generated />
using System;
using ETicket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETicket.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190118032053_ModelAdd")]
    partial class ModelAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ETicketAngular.Models.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CountryId");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ETicketAngular.Models.Countries", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ETicketAngular.Models.Deliveries", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("ETicketAngular.Models.Events", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventDescription")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("EventEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("datetime");

                    b.Property<int>("EventTicketPurchaseLimit");

                    b.Property<int?>("HotelReservationId");

                    b.Property<int>("PlaceId");

                    b.Property<int?>("TourId");

                    b.Property<int?>("TransportReservationId");

                    b.HasKey("EventId");

                    b.HasIndex("HotelReservationId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("TourId");

                    b.HasIndex("TransportReservationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ETicketAngular.Models.HotelReservations", b =>
                {
                    b.Property<int>("HotelReservationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<DateTime>("HotelReservationEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HotelReservationStart")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomId");

                    b.HasKey("HotelReservationId");

                    b.HasIndex("EventId");

                    b.HasIndex("RoomId");

                    b.ToTable("HotelReservations");
                });

            modelBuilder.Entity("ETicketAngular.Models.Hotels", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("HotelAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HotelDescription")
                        .HasMaxLength(500);

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HotelPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<int>("HotelRoomsNumber");

                    b.HasKey("HotelId");

                    b.HasIndex("CityId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("ETicketAngular.Models.PerformerCategories", b =>
                {
                    b.Property<int>("PerformerCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PerformerCategoryName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PerformerCategoryId");

                    b.ToTable("PerformerCategories");
                });

            modelBuilder.Entity("ETicketAngular.Models.Performers", b =>
                {
                    b.Property<int>("PerformerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PerformerCategoryId");

                    b.Property<string>("PerformerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PerformerId");

                    b.HasIndex("PerformerCategoryId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("ETicketAngular.Models.Places", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("PlaceAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("PlaceCapacity");

                    b.Property<string>("PlaceDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PlaceId");

                    b.HasIndex("CityId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("ETicketAngular.Models.Purchases", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryId");

                    b.Property<int?>("HotelReservationId");

                    b.Property<string>("Id");

                    b.Property<string>("PurchaseSelectedRow")
                        .HasMaxLength(10);

                    b.Property<string>("PurchaseSelectedRowSeat")
                        .HasMaxLength(10);

                    b.Property<DateTime>("PurchaseTicketDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ReliefId");

                    b.Property<int>("TicketId");

                    b.Property<int?>("TransportReservationId");

                    b.HasKey("PurchaseId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("HotelReservationId");

                    b.HasIndex("Id");

                    b.HasIndex("ReliefId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TransportReservationId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("ETicketAngular.Models.Reliefs", b =>
                {
                    b.Property<int>("ReliefId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ReliefPercent")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("ReliefType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ReliefId");

                    b.ToTable("Reliefs");
                });

            modelBuilder.Entity("ETicketAngular.Models.Rooms", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HotelId");

                    b.Property<bool>("RoomAvailable");

                    b.Property<int>("RoomBeds");

                    b.Property<string>("RoomDescription")
                        .HasMaxLength(500);

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("RoomPriceForNight")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ETicketAngular.Models.Sectors", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlaceId");

                    b.Property<int>("SectorAvailability");

                    b.Property<int?>("SectorCapacity");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("SectorRowPlaces");

                    b.Property<int?>("SectorRows");

                    b.HasKey("SectorId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("ETicketAngular.Models.Tickets", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<int?>("SectorId");

                    b.Property<string>("TicketDescription")
                        .HasMaxLength(500);

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.HasIndex("SectorId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ETicketAngular.Models.Tours", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PerformerId");

                    b.Property<string>("TourDescription")
                        .HasMaxLength(500);

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TourId");

                    b.HasIndex("PerformerId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("ETicketAngular.Models.TransportReservations", b =>
                {
                    b.Property<int>("TransportReservationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<int>("EventId");

                    b.Property<int>("TransportId");

                    b.Property<string>("TransportReservationAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("TransportReservationEnd")
                        .HasColumnType("datetime");

                    b.Property<int>("TransportReservationPrice");

                    b.Property<DateTime>("TransportReservationStart")
                        .HasColumnType("datetime");

                    b.HasKey("TransportReservationId");

                    b.HasIndex("CityId");

                    b.HasIndex("EventId");

                    b.HasIndex("TransportId");

                    b.ToTable("TransportReservations");
                });

            modelBuilder.Entity("ETicketAngular.Models.Transports", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TransportDescription")
                        .HasMaxLength(50);

                    b.Property<string>("TransportName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("TransportId");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ETicketAngular.Models.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int>("CountryId");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UserBirthdate")
                        .HasColumnType("date");

                    b.Property<string>("UserCity")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("UserFirstname")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UserLastLog")
                        .HasColumnType("datetime");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(20);

                    b.Property<string>("UserSex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("UserSurname")
                        .HasMaxLength(50);

                    b.HasIndex("CountryId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");
                });

            modelBuilder.Entity("ETicketAngular.Models.Cities", b =>
                {
                    b.HasOne("ETicketAngular.Models.Countries", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Cities_ToCountries");
                });

            modelBuilder.Entity("ETicketAngular.Models.Events", b =>
                {
                    b.HasOne("ETicketAngular.Models.HotelReservations", "HotelReservation")
                        .WithMany("Events")
                        .HasForeignKey("HotelReservationId")
                        .HasConstraintName("FK_Events_ToHotelReservations");

                    b.HasOne("ETicketAngular.Models.Places", "Place")
                        .WithMany("Events")
                        .HasForeignKey("PlaceId")
                        .HasConstraintName("FK_Events_ToPlaces");

                    b.HasOne("ETicketAngular.Models.Tours", "Tour")
                        .WithMany("Events")
                        .HasForeignKey("TourId")
                        .HasConstraintName("FK_Events_ToTours");

                    b.HasOne("ETicketAngular.Models.TransportReservations", "TransportReservation")
                        .WithMany("Events")
                        .HasForeignKey("TransportReservationId")
                        .HasConstraintName("FK_Events_ToTransportReservations");
                });

            modelBuilder.Entity("ETicketAngular.Models.HotelReservations", b =>
                {
                    b.HasOne("ETicketAngular.Models.Events", "Event")
                        .WithMany("HotelReservations")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_HotelReservations_ToEvents");

                    b.HasOne("ETicketAngular.Models.Rooms", "Room")
                        .WithMany("HotelReservations")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK_HotelReservations_ToRooms");
                });

            modelBuilder.Entity("ETicketAngular.Models.Hotels", b =>
                {
                    b.HasOne("ETicketAngular.Models.Cities", "City")
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Hotels_ToCities");
                });

            modelBuilder.Entity("ETicketAngular.Models.Performers", b =>
                {
                    b.HasOne("ETicketAngular.Models.PerformerCategories", "PerformerCategory")
                        .WithMany("Performers")
                        .HasForeignKey("PerformerCategoryId")
                        .HasConstraintName("FK_Performers_ToPerformerCategories");
                });

            modelBuilder.Entity("ETicketAngular.Models.Places", b =>
                {
                    b.HasOne("ETicketAngular.Models.Cities", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Places_ToCities");
                });

            modelBuilder.Entity("ETicketAngular.Models.Purchases", b =>
                {
                    b.HasOne("ETicketAngular.Models.Deliveries", "Delivery")
                        .WithMany("Purchases")
                        .HasForeignKey("DeliveryId")
                        .HasConstraintName("FK_Purchases_ToDeliveries");

                    b.HasOne("ETicketAngular.Models.HotelReservations", "HotelReservation")
                        .WithMany("Purchases")
                        .HasForeignKey("HotelReservationId")
                        .HasConstraintName("FK_Purchases_ToHotelReservations");

                    b.HasOne("ETicketAngular.Models.Users", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_Purchases_ToUsers");

                    b.HasOne("ETicketAngular.Models.Reliefs", "Relief")
                        .WithMany("Purchases")
                        .HasForeignKey("ReliefId")
                        .HasConstraintName("FK_Purchases_ToReliefs");

                    b.HasOne("ETicketAngular.Models.Tickets", "Ticket")
                        .WithMany("Purchases")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK_Purchases_ToTickets");

                    b.HasOne("ETicketAngular.Models.TransportReservations", "TransportReservation")
                        .WithMany("Purchases")
                        .HasForeignKey("TransportReservationId")
                        .HasConstraintName("FK_Purchases_ToTransportReservations");
                });

            modelBuilder.Entity("ETicketAngular.Models.Rooms", b =>
                {
                    b.HasOne("ETicketAngular.Models.Hotels", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .HasConstraintName("FK_Rooms_ToHotels");
                });

            modelBuilder.Entity("ETicketAngular.Models.Sectors", b =>
                {
                    b.HasOne("ETicketAngular.Models.Places", "Place")
                        .WithMany("Sectors")
                        .HasForeignKey("PlaceId")
                        .HasConstraintName("FK_Sectors_ToPlaces");
                });

            modelBuilder.Entity("ETicketAngular.Models.Tickets", b =>
                {
                    b.HasOne("ETicketAngular.Models.Events", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Tickets_ToEvents");

                    b.HasOne("ETicketAngular.Models.Sectors", "Sector")
                        .WithMany("Tickets")
                        .HasForeignKey("SectorId")
                        .HasConstraintName("FK_Tickets_ToSectors");
                });

            modelBuilder.Entity("ETicketAngular.Models.Tours", b =>
                {
                    b.HasOne("ETicketAngular.Models.Performers", "Performer")
                        .WithMany("Tours")
                        .HasForeignKey("PerformerId")
                        .HasConstraintName("FK_Tours_ToPerformers");
                });

            modelBuilder.Entity("ETicketAngular.Models.TransportReservations", b =>
                {
                    b.HasOne("ETicketAngular.Models.Cities", "City")
                        .WithMany("TransportReservations")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_TransportReservations_ToCities");

                    b.HasOne("ETicketAngular.Models.Events", "Event")
                        .WithMany("TransportReservations")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_TransportReservations_ToEvents");

                    b.HasOne("ETicketAngular.Models.Transports", "Transport")
                        .WithMany("TransportReservations")
                        .HasForeignKey("TransportId")
                        .HasConstraintName("FK_TransportReservations_ToTransports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ETicketAngular.Models.Users", b =>
                {
                    b.HasOne("ETicketAngular.Models.Countries", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Users_ToCountries");
                });
#pragma warning restore 612, 618
        }
    }
}
